<?php
/**
 * 生成表.
 * User: Administrator
 * Date: 2019/11/3 0003
 * Time: 0:28
 */

namespace EasySwoole\ORM\Tests;

use EasySwoole\ORM\Db\Config;
use EasySwoole\ORM\Db\Connection;
use EasySwoole\ORM\DbManager;
use EasySwoole\ORM\Tests\models\TestTimeStampModel;
use EasySwoole\ORM\Utility\TableObjectGeneration;
use PHPUnit\Framework\TestCase;

class TimeStampTableGenerationTest extends TestCase
{
    /**
     * @var $generation TableObjectGeneration
     */
    protected $generation;
    /**
     * @var $connection Connection
     */
    protected $connection;

    protected $tableName = 'tiamstamp_test';


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $config = new Config(MYSQL_CONFIG);
        $connection = new Connection($config);
        $this->connection = $connection;

        DbManager::getInstance()->addConnection($this->connection);
        TestTimeStampModel::create();

        $this->generation = new TableObjectGeneration($connection, $this->tableName);
    }

    function testGetTableInfo()
    {
        $data = $this->generation->getTableColumnsInfo();
        $this->assertIsArray($data);
    }
}
