<?php

namespace EasySwoole\ORM\Tests;

use EasySwoole\ORM\AbstractModel;
use EasySwoole\ORM\Db\Config;
use EasySwoole\ORM\Db\Connection;
use EasySwoole\ORM\DbManager;
use EasySwoole\ORM\Tests\models\TestWhereModel;
use PHPUnit\Framework\TestCase;


class WhereTest extends TestCase
{
    /**
     * @var $connection Connection
     */
    protected $connection;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $config = new Config(MYSQL_CONFIG);
        $config->setReturnCollection(true);
        $this->connection = new Connection($config);
        DbManager::getInstance()->addConnection($this->connection);
        $connection = DbManager::getInstance()->getConnection();
        $this->assertTrue($connection === $this->connection);

        TestWhereModel::create();
    }

    public function testWhereIn()
    {
        $ids = [];
        $ids[] = TestWhereModel::create(['content' => 'a,b,c'])->save();
        $ids[] = TestWhereModel::create(['content' => 'a,b,c,d'])->save();
        $ids[] = TestWhereModel::create(['content' => 'a,b,c,d,e'])->save();

        $model = TestWhereModel::create();
        $ret = $model->where('content', 'a,b,c')->get();
        $this->assertInstanceOf(AbstractModel::class, $ret);
        $this->assertEquals("SELECT  * FROM `test_where` WHERE  `content` = 'a,b,c'  LIMIT 1", $model->lastQuery()->getLastQuery());
        $this->assertEquals($ids[0], $ret->id);

        $model = TestWhereModel::create();
        $ret = $model->where('id', $ids, 'IN')->all();
        $idStrings = implode(', ', $ids);
        $this->assertEquals("SELECT  * FROM `test_where` WHERE  `id` IN ( {$idStrings} ) ", $model->lastQuery()->getLastQuery());
        $this->assertEquals($ids, array_column($ret->toArray(), 'id'));

        try {
            $idStrings = implode(', ', $ids);
            TestWhereModel::create()->where('id', $idStrings, 'IN')->all();
        } catch (\Throwable $e) {
            $this->assertEquals('foreach() argument must be of type array|object, string given', $e->getMessage());
        }
    }


    public function testDeleteAll()
    {
        $res = TestWhereModel::create()->destroy(null, true);
        $this->assertIsInt($res);
    }
}
