<?php
/**
 * Created by PhpStorm.
 * User: Siam
 * Date: 2019/11/28
 * Time: 15:43
 */

namespace EasySwoole\ORM\Tests\Swoole5x;

use PHPUnit\Framework\TestCase;
use Swoole\Coroutine\MySQL;

class SwooleTest extends TestCase
{
    /** @var MySQL */
    protected $client;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        if (version_compare(swoole_version(), '5.0.0', '>=')) {
            return;
        }

        $swoole_mysql = new MySQL();
        $swoole_mysql->connect(MYSQL_CONFIG);
        $this->client = $swoole_mysql;
    }

    public function testInsert()
    {
        if (version_compare(swoole_version(), '5.0.0', '>=')) {
            $this->assertSame(1, 1);
            return;
        }

        $false = $this->client->query("insert into user_test_list (ttttt) values (1)");
        $this->assertFalse($false);
    }
}
